- name: variables from files
  hosts: local
  connection: local
  vars_filess:
  - course.yaml
  tasks: 
  - name: print  course informatio
    ansible.builtin.debug:
     msg: "course is {{ COURSE }}, Duration is {{DURATION}}, trainer is {{TRAINER}}"