- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print course inforamtion
    ansible.builtin.debug:
     msg: "course is {{ COURSE }}, duration is {{ DUARTION: }}, trainer is {{ TRAINER }}"