- name: variables from files
  hosts: local
  connection: local
  tasks:
  - name: print course information
    ansible.builtin.debug:
     msg: "Course is {{ COURSE}}, duration is {{ DUARTION}}, trainer is {{ TRAINER }}"