- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.packages:
        name: HELLO {{ "ITEM "}}
        state: installed
    loop:
    - gcc
    - mysql
    - git
    - zip
